// Code generated by tygo. DO NOT EDIT.

//////////
// source: service.go

export interface Service {
}

//////////
// source: types.go

export interface ListCircuitsResponse {
  circuit_id: string;
  name: string;
  country: string;
  first_race_year?: number /* int32 */;
  last_race_year?: number /* int32 */;
  location: string;
  race_count: number /* int */;
}
export interface CircuitRaceSummary {
  raceId: any /* dbtypes.Int4 */;
  date?: any /* dbtypes.Date */;
  name: string;
}
export interface CircuitRace {
  raceId: number /* int */;
  date: any /* dbtypes.Date */;
  layoutId: string;
  name: string;
  winnerId: string;
  winnerName: string;
}
export interface CircuitSummaryResponse {
  circuitId: string;
  name: string;
  circuitType: string;
  country: string;
  countryId: string;
  firstRace: CircuitRaceSummary;
  lastRace: CircuitRaceSummary;
  layoutId: string;
  previousNames: string[];
  raceCount: number /* int */;
  turns: number /* int */;
  races: CircuitRace[];
}
