// Code generated by tygo. DO NOT EDIT.

//////////
// source: service.go

export interface Service {
}

//////////
// source: types.go

export interface ListCircuitsResponse {
  circuit_id: string;
  name: string;
  country: string;
  first_race_year?: number /* int32 */;
  last_race_year?: number /* int32 */;
  location: string;
  race_count: number /* int */;
}
