// Code generated by tygo. DO NOT EDIT.

//////////
// source: handler.go

/**
 * Handler serves constructor endpoints.
 */
export interface Handler {
}

//////////
// source: service.go

/**
 * Service reads constructor data.
 */
export interface Service {
}

//////////
// source: types.go

/**
 * ConstructorResponse is one row of the GET /constructors list.
 */
export interface ConstructorResponse {
  id: string;
  name: string;
  color: string;
  /**
   * Dates use omitempty: absent dates are omitted from the object entirely
   * (matching the previous service, which emitted undefined for missing dates).
   */
  firstRaceDate?: string;
  lastRaceDate?: string;
  championships: number /* int32 */;
  wins: number /* int32 */;
  podiums: number /* int32 */;
}
