// Code generated by tygo. DO NOT EDIT.

//////////
// source: service.go

export interface Service {
}

//////////
// source: types.go

export interface ConstructorResponse {
  id: string;
  name: string;
  color: string;
  firstRaceDate?: any /* dbtypes.Date */;
  lastRaceDate?: any /* dbtypes.Date */;
  championships: number /* int32 */;
  wins: number /* int32 */;
  podiums: number /* int32 */;
}
