// Code generated by tygo. DO NOT EDIT.

//////////
// source: service.go

export interface Service {
}

//////////
// source: types.go

export interface DriverSummary {
  code: string;
  name: string;
  country: string;
  countryCode: string;
  starts: number /* int32 */;
  wins: number /* int32 */;
  podiums: number /* int32 */;
  poles: number /* int32 */;
  championships: number /* int32 */;
  seasons: driverSeasonSummary[];
}
export interface DriverShortSummary {
  id: string;
  code: string;
  name: string;
  starts: number /* int32 */;
  wins: number /* int32 */;
  podiums: number /* int32 */;
  poles: number /* int32 */;
  championships: number /* int32 */;
  isActive: boolean;
  constructorColor: string;
  firstYear?: number /* int32 */;
  lastYear?: number /* int32 */;
}
