// Code generated by tygo. DO NOT EDIT.

//////////
// source: handler.go

/**
 * Handler serves season endpoints.
 */
export interface Handler {
}

//////////
// source: service.go

/**
 * Service reads season data.
 */
export interface Service {
}

//////////
// source: types.go

/**
 * SeasonResponse is one row of the GET /seasons list. Field order is irrelevant
 * to clients (JSON is an object); the json tags define the wire contract.
 */
export interface SeasonResponse {
  season: number /* int32 */;
  raceCount: number /* int32 */;
  constructorCount: number /* int32 */;
  wdc: WDC;
  /**
   * Wcc is null for seasons predating the World Constructors' Championship.
   * No omitempty: the key is always present, value null when absent.
   */
  wcc?: WCC;
}
/**
 * WDC is a season's World Drivers' Champion.
 */
export interface WDC {
  id: string;
  name: string;
  countryCode: string;
}
/**
 * WCC is a season's World Constructors' Champion.
 */
export interface WCC {
  id: string;
  name: string;
  color: string;
}
