// Code generated by tygo. DO NOT EDIT.

//////////
// source: service.go

export interface Service {
}

//////////
// source: types.go

export interface SeasonResponse {
  season: number /* int32 */;
  raceCount: number /* int32 */;
  constructorCount: number /* int32 */;
  wdc: WDC;
  wcc?: WCC;
}
export interface WDC {
  id: string;
  name: string;
  countryCode: string;
}
export interface WCC {
  id: string;
  name: string;
  color: string;
}
