drs:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PGHOST', 'localhost') }}"
      port: "{{ env_var('PGPORT', '5432') | int }}"
      user: "{{ env_var('PGUSER', 'postgres') }}"
      password: "{{ env_var('PGPASSWORD', '') }}"
      dbname: "{{ env_var('PGDATABASE', 'drs') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'dbt') }}"
      threads: 4

