// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: circuits.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCircuitInfo = `-- name: GetCircuitInfo :one
SELECT
    circuit_id,
    circuit_full_name as name,
    circuit_type,
    country,
    country_code,
    country_id,
    first_race_id,
    first_race_date,
    first_race_name,
    last_race_id,
    last_race_date,
    last_race_name,
    current_layout_id,
    previous_names,
    race_count,
    turns
FROM effone.circuits
WHERE circuit_id = $1
`

type GetCircuitInfoRow struct {
	CircuitID       string
	Name            string
	CircuitType     string
	Country         string
	CountryCode     string
	CountryID       string
	FirstRaceID     pgtype.Int4
	FirstRaceDate   pgtype.Date
	FirstRaceName   pgtype.Text
	LastRaceID      pgtype.Int4
	LastRaceDate    pgtype.Date
	LastRaceName    pgtype.Text
	CurrentLayoutID pgtype.Text
	PreviousNames   []string
	RaceCount       int32
	Turns           int32
}

func (q *Queries) GetCircuitInfo(ctx context.Context, circuitID string) (GetCircuitInfoRow, error) {
	row := q.db.QueryRow(ctx, getCircuitInfo, circuitID)
	var i GetCircuitInfoRow
	err := row.Scan(
		&i.CircuitID,
		&i.Name,
		&i.CircuitType,
		&i.Country,
		&i.CountryCode,
		&i.CountryID,
		&i.FirstRaceID,
		&i.FirstRaceDate,
		&i.FirstRaceName,
		&i.LastRaceID,
		&i.LastRaceDate,
		&i.LastRaceName,
		&i.CurrentLayoutID,
		&i.PreviousNames,
		&i.RaceCount,
		&i.Turns,
	)
	return i, err
}

const getRacesByCircuitId = `-- name: GetRacesByCircuitId :many
SELECT
    race_id,
    race_date,
    circuit_layout_id,
    race_official_name,
    winner_driver_id,
    winner_driver_name
FROM effone.races
WHERE circuit_id = $1
ORDER BY race_date DESC
`

type GetRacesByCircuitIdRow struct {
	RaceID           int32
	RaceDate         pgtype.Date
	CircuitLayoutID  string
	RaceOfficialName string
	WinnerDriverID   pgtype.Text
	WinnerDriverName pgtype.Text
}

func (q *Queries) GetRacesByCircuitId(ctx context.Context, circuitID string) ([]GetRacesByCircuitIdRow, error) {
	rows, err := q.db.Query(ctx, getRacesByCircuitId, circuitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRacesByCircuitIdRow
	for rows.Next() {
		var i GetRacesByCircuitIdRow
		if err := rows.Scan(
			&i.RaceID,
			&i.RaceDate,
			&i.CircuitLayoutID,
			&i.RaceOfficialName,
			&i.WinnerDriverID,
			&i.WinnerDriverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCircuits = `-- name: ListCircuits :many
SELECT
    circuit_id,
    circuit_name as name,
    country,
    CASE WHEN first_race_date IS NOT NULL THEN date_part('year', first_race_date)::INTEGER END AS first_race_year,
    CASE WHEN last_race_date IS NOT NULL THEN date_part('year', last_race_date)::INTEGER END AS last_race_year,
    location,
    race_count
FROM effone.circuits
ORDER BY last_race_date DESC
`

type ListCircuitsRow struct {
	CircuitID     string
	Name          string
	Country       string
	FirstRaceYear pgtype.Int4
	LastRaceYear  pgtype.Int4
	Location      string
	RaceCount     int32
}

func (q *Queries) ListCircuits(ctx context.Context) ([]ListCircuitsRow, error) {
	rows, err := q.db.Query(ctx, listCircuits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCircuitsRow
	for rows.Next() {
		var i ListCircuitsRow
		if err := rows.Scan(
			&i.CircuitID,
			&i.Name,
			&i.Country,
			&i.FirstRaceYear,
			&i.LastRaceYear,
			&i.Location,
			&i.RaceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
