// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: circuits.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCircuits = `-- name: ListCircuits :many
SELECT
    circuit_id,
    circuit_name as name,
    country,
    first_race_date,
    last_race_date,
    location,
    race_count
FROM effone.circuits
ORDER BY last_race_date DESC
`

type ListCircuitsRow struct {
	CircuitID     string
	Name          string
	Country       string
	FirstRaceDate pgtype.Date
	LastRaceDate  pgtype.Date
	Location      string
	RaceCount     int32
}

func (q *Queries) ListCircuits(ctx context.Context) ([]ListCircuitsRow, error) {
	rows, err := q.db.Query(ctx, listCircuits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCircuitsRow
	for rows.Next() {
		var i ListCircuitsRow
		if err := rows.Scan(
			&i.CircuitID,
			&i.Name,
			&i.Country,
			&i.FirstRaceDate,
			&i.LastRaceDate,
			&i.Location,
			&i.RaceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
