// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: constructors.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listConstructors = `-- name: ListConstructors :many
SELECT
    constructor_id AS id,
    constructor_name AS name,
    primary_color_hex AS color,
    first_race_date,
    last_race_date,
    championship_count AS championships,
    win_count AS wins,
    podium_count AS podiums
FROM effone.constructors
ORDER BY constructor_name
`

type ListConstructorsRow struct {
	ID            string
	Name          string
	Color         string
	FirstRaceDate pgtype.Date
	LastRaceDate  pgtype.Date
	Championships int32
	Wins          int32
	Podiums       int32
}

func (q *Queries) ListConstructors(ctx context.Context) ([]ListConstructorsRow, error) {
	rows, err := q.db.Query(ctx, listConstructors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConstructorsRow
	for rows.Next() {
		var i ListConstructorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.FirstRaceDate,
			&i.LastRaceDate,
			&i.Championships,
			&i.Wins,
			&i.Podiums,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
