// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: drivers.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jsec/drs/internal/dbtypes"
)

const getDriverSeason = `-- name: GetDriverSeason :one
SELECT
    d.driver_code AS code,
    d.driver_name AS name,
    d.nationality AS country,
    d.nationality_country_code AS country_code,
    c.constructor_name,
    c.primary_color_hex AS constructor_color,
    (
        SELECT rr.car_number
        FROM effone.race_results rr
        WHERE rr.season = dss.season
            AND rr.driver_id = dss.driver_id
        ORDER BY rr.race_round DESC
        LIMIT 1
    ) AS car_number,
    coalesce(dss.final_points, dss.total_points)::double precision AS points,
    dss.final_position_text AS position,
    dss.win_count AS wins,
    dss.podium_count AS podiums,
    dss.qualifying_p1_count AS poles
FROM effone.driver_season_summaries dss
    JOIN effone.drivers d ON dss.driver_id = d.driver_id
    JOIN effone.constructors c ON dss.constructor_id = c.constructor_id
WHERE dss.season = $1
    AND dss.driver_id = $2
`

type GetDriverSeasonParams struct {
	Season   int32
	DriverID string
}

type GetDriverSeasonRow struct {
	Code             string
	Name             string
	Country          string
	CountryCode      string
	ConstructorName  string
	ConstructorColor string
	CarNumber        dbtypes.Int4
	Points           float64
	Position         pgtype.Text
	Wins             int32
	Podiums          int32
	Poles            int32
}

func (q *Queries) GetDriverSeason(ctx context.Context, arg GetDriverSeasonParams) (GetDriverSeasonRow, error) {
	row := q.db.QueryRow(ctx, getDriverSeason, arg.Season, arg.DriverID)
	var i GetDriverSeasonRow
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Country,
		&i.CountryCode,
		&i.ConstructorName,
		&i.ConstructorColor,
		&i.CarNumber,
		&i.Points,
		&i.Position,
		&i.Wins,
		&i.Podiums,
		&i.Poles,
	)
	return i, err
}

const getDriverSummary = `-- name: GetDriverSummary :one
WITH current_season AS (
    SELECT max(season) AS season
    FROM effone.driver_season_constructor_summaries
),
active_drivers AS (
    SELECT DISTINCT ON (driver_id)
        driver_id,
        constructor_id
    FROM effone.driver_season_constructor_summaries
    WHERE season = (SELECT season FROM current_season)
    ORDER BY driver_id, constructor_sequence DESC
)
SELECT
    d.driver_code AS code,
    d.driver_name AS name,
    d.nationality AS country,
    d.nationality_country_code AS country_code,
    d.start_count AS starts,
    d.win_count AS wins,
    d.podium_count AS podiums,
    d.qualifying_p1_count AS poles,
    d.championship_count AS championships,
    d.first_race_date,
    d.last_race_date,
    a.driver_id IS NOT NULL AS is_active,
    c.primary_color_hex AS constructor_color
FROM effone.drivers d
LEFT JOIN active_drivers a ON d.driver_id = a.driver_id
LEFT JOIN effone.constructors c ON a.constructor_id = c.constructor_id
WHERE d.driver_id = $1
`

type GetDriverSummaryRow struct {
	Code             string
	Name             string
	Country          string
	CountryCode      string
	Starts           int32
	Wins             int32
	Podiums          int32
	Poles            int32
	Championships    int32
	FirstRaceDate    dbtypes.Date
	LastRaceDate     dbtypes.Date
	IsActive         pgtype.Bool
	ConstructorColor pgtype.Text
}

func (q *Queries) GetDriverSummary(ctx context.Context, driverID string) (GetDriverSummaryRow, error) {
	row := q.db.QueryRow(ctx, getDriverSummary, driverID)
	var i GetDriverSummaryRow
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Country,
		&i.CountryCode,
		&i.Starts,
		&i.Wins,
		&i.Podiums,
		&i.Poles,
		&i.Championships,
		&i.FirstRaceDate,
		&i.LastRaceDate,
		&i.IsActive,
		&i.ConstructorColor,
	)
	return i, err
}

const listDriverSeasonRaces = `-- name: ListDriverSeasonRaces :many
SELECT DISTINCT ON (rr.race_round)
    rr.race_round,
    r.race_name,
    rr.grid_position,
    rr.position_text AS position_label,
    rr.finish_position AS position,
    rr.status_category,
    rr.points::double precision AS points,
    sr.position_text AS sprint_position_label,
    coalesce(sr.points, 0)::double precision AS sprint_points
FROM effone.race_results rr
    JOIN effone.races r ON rr.race_id = r.race_id
    LEFT JOIN effone.sprint_results sr
        ON rr.race_id = sr.race_id
        AND rr.driver_id = sr.driver_id
WHERE rr.season = $1
    AND rr.driver_id = $2
ORDER BY rr.race_round, rr.finish_order
`

type ListDriverSeasonRacesParams struct {
	Season   int32
	DriverID string
}

type ListDriverSeasonRacesRow struct {
	RaceRound           int32
	RaceName            string
	GridPosition        dbtypes.Int4
	PositionLabel       string
	Position            dbtypes.Int4
	StatusCategory      string
	Points              float64
	SprintPositionLabel pgtype.Text
	SprintPoints        float64
}

func (q *Queries) ListDriverSeasonRaces(ctx context.Context, arg ListDriverSeasonRacesParams) ([]ListDriverSeasonRacesRow, error) {
	rows, err := q.db.Query(ctx, listDriverSeasonRaces, arg.Season, arg.DriverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDriverSeasonRacesRow
	for rows.Next() {
		var i ListDriverSeasonRacesRow
		if err := rows.Scan(
			&i.RaceRound,
			&i.RaceName,
			&i.GridPosition,
			&i.PositionLabel,
			&i.Position,
			&i.StatusCategory,
			&i.Points,
			&i.SprintPositionLabel,
			&i.SprintPoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDriverSeasons = `-- name: ListDriverSeasons :many
SELECT
    dscs.season,
    c.constructor_name,
    c.primary_color_hex AS constructor_color,
    dscs.race_start_count AS starts,
    dscs.win_count AS wins,
    dscs.podium_count AS podiums,
    dscs.qualifying_p1_count AS poles,
    dss.final_points::INT AS points,
    dss.final_position_text AS position
FROM effone.driver_season_constructor_summaries dscs
    JOIN effone.driver_season_summaries dss
        ON dscs.season = dss.season
        AND dscs.driver_id = dss.driver_id
    JOIN effone.constructors c ON dscs.constructor_id = c.constructor_id
WHERE dscs.driver_id = $1
ORDER BY dscs.season DESC, dscs.constructor_sequence
`

type ListDriverSeasonsRow struct {
	Season           int32
	ConstructorName  string
	ConstructorColor string
	Starts           int32
	Wins             int32
	Podiums          int32
	Poles            int32
	Points           int32
	Position         pgtype.Text
}

func (q *Queries) ListDriverSeasons(ctx context.Context, driverID string) ([]ListDriverSeasonsRow, error) {
	rows, err := q.db.Query(ctx, listDriverSeasons, driverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDriverSeasonsRow
	for rows.Next() {
		var i ListDriverSeasonsRow
		if err := rows.Scan(
			&i.Season,
			&i.ConstructorName,
			&i.ConstructorColor,
			&i.Starts,
			&i.Wins,
			&i.Podiums,
			&i.Poles,
			&i.Points,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDrivers = `-- name: ListDrivers :many
WITH current_season AS (
    SELECT max(season) AS season
    FROM effone.driver_season_constructor_summaries
),
active_drivers AS (
    SELECT DISTINCT ON (driver_id)
        driver_id,
        constructor_id
    FROM effone.driver_season_constructor_summaries
    WHERE season = (SELECT season FROM current_season)
    ORDER BY driver_id, constructor_sequence DESC
)
SELECT
    d.driver_id as id,
    d.driver_code AS code,
    d.driver_name AS name,
    d.start_count AS starts,
    d.win_count AS wins,
    d.podium_count AS podiums,
    d.qualifying_p1_count AS poles,
    d.championship_count AS championships,
    d.first_race_date,
    d.last_race_date,
    a.driver_id IS NOT NULL AS is_active,
    c.primary_color_hex AS constructor_color
FROM effone.drivers d
LEFT JOIN active_drivers a ON d.driver_id = a.driver_id
LEFT JOIN effone.constructors c ON a.constructor_id = c.constructor_id
`

type ListDriversRow struct {
	ID               string
	Code             string
	Name             string
	Starts           int32
	Wins             int32
	Podiums          int32
	Poles            int32
	Championships    int32
	FirstRaceDate    dbtypes.Date
	LastRaceDate     dbtypes.Date
	IsActive         pgtype.Bool
	ConstructorColor pgtype.Text
}

func (q *Queries) ListDrivers(ctx context.Context) ([]ListDriversRow, error) {
	rows, err := q.db.Query(ctx, listDrivers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDriversRow
	for rows.Next() {
		var i ListDriversRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Starts,
			&i.Wins,
			&i.Podiums,
			&i.Poles,
			&i.Championships,
			&i.FirstRaceDate,
			&i.LastRaceDate,
			&i.IsActive,
			&i.ConstructorColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
