// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EffoneCircuit struct {
	CircuitFullName       string
	CircuitID             string
	CircuitName           string
	CircuitType           string
	Country               string
	CountryID             string
	Direction             string
	FirstRaceDate         pgtype.Date
	FirstRaceID           pgtype.Int4
	FirstRaceName         pgtype.Text
	LastRaceDate          pgtype.Date
	LastRaceID            pgtype.Int4
	LastRaceName          pgtype.Text
	Latitude              pgtype.Numeric
	LengthKm              pgtype.Numeric
	Location              string
	Longitude             pgtype.Numeric
	CurrentLayoutID       pgtype.Text
	CurrentLayoutLengthKm pgtype.Numeric
	CurrentLayoutTurns    pgtype.Int4
	PreviousNames         []string
	RaceCount             int32
	RefreshID             int64
	Turns                 int32
}

type EffoneCircuitLayout struct {
	CircuitLayoutID        string
	CircuitID              string
	IsCurrentConfiguration bool
	LengthKm               pgtype.Numeric
	Turns                  int32
	RaceCount              int32
	FirstRaceID            pgtype.Int4
	FirstRaceName          pgtype.Text
	FirstRaceDate          pgtype.Date
	LastRaceID             pgtype.Int4
	LastRaceName           pgtype.Text
	LastRaceDate           pgtype.Date
	RefreshID              int64
}

type EffoneConstructor struct {
	ChampionshipCount    int32
	ConstructorFullName  string
	ConstructorID        string
	ConstructorName      string
	CountryID            string
	EntryCount           int32
	FastestLapCount      int32
	FirstRaceDate        pgtype.Date
	FirstRaceID          pgtype.Int4
	FirstRaceName        pgtype.Text
	LastRaceDate         pgtype.Date
	LastRaceID           pgtype.Int4
	LastRaceName         pgtype.Text
	Nationality          string
	PodiumCount          int32
	PrimaryColorHex      string
	QualifyingEntryCount int32
	QualifyingP1Count    int32
	RaceEntryCount       int32
	RaceStartCount       int32
	RefreshID            int64
	SecondaryColorHex    pgtype.Text
	SprintEntryCount     int32
	SprintStartCount     int32
	StartCount           int32
	TotalPoints          pgtype.Numeric
	TotalPointsX100      int32
	WinCount             int32
}

type EffoneConstructorSeasonSummary struct {
	AverageQualifyingPosition pgtype.Numeric
	ChampionshipWon           bool
	ConstructorID             string
	ConstructorName           string
	EngineManufacturerID      string
	EntryCount                int32
	FastestLapCount           int32
	FinalOrder                int32
	FinalPoints               pgtype.Numeric
	FinalPointsX100           pgtype.Int4
	FinalPosition             pgtype.Int4
	FinalPositionText         pgtype.Text
	PodiumCount               int32
	PointsDelta               pgtype.Numeric
	PointsDeltaX100           int32
	QualifyingEntryCount      int32
	QualifyingP1Count         int32
	QualifyingPositionCount   int32
	RaceEntryCount            int32
	RacePoints                pgtype.Numeric
	RacePointsX100            int32
	RaceStartCount            int32
	RefreshID                 int64
	Season                    int32
	SprintEntryCount          int32
	SprintPoints              pgtype.Numeric
	SprintPointsX100          int32
	SprintStartCount          int32
	StartCount                int32
	TotalPoints               pgtype.Numeric
	TotalPointsX100           int32
	WinCount                  int32
}

type EffoneConstructorStandingsSnapshot struct {
	ChampionshipWon      bool
	ConstructorID        string
	ConstructorName      string
	EngineManufacturerID string
	Points               pgtype.Numeric
	PointsGained         pgtype.Numeric
	PointsGainedX100     pgtype.Int4
	PointsX100           int32
	Position             pgtype.Int4
	PositionChange       pgtype.Int4
	PositionText         string
	PreviousPoints       pgtype.Numeric
	PreviousPointsX100   pgtype.Int4
	PreviousPosition     pgtype.Int4
	RaceID               int32
	RaceRound            int32
	RefreshID            int64
	Season               int32
}

type EffoneDriver struct {
	ChampionshipCount            int32
	CountryOfBirthID             string
	DateOfBirth                  pgtype.Date
	DateOfDeath                  pgtype.Date
	DriverCode                   string
	DriverFullName               string
	DriverID                     string
	DriverName                   string
	DriverNumber                 pgtype.Int4
	EntryCount                   int32
	FastestLapCount              int32
	FirstName                    string
	FirstRaceDate                pgtype.Date
	FirstRaceID                  pgtype.Int4
	FirstRaceName                pgtype.Text
	Gender                       string
	LastName                     string
	LastRaceDate                 pgtype.Date
	LastRaceID                   pgtype.Int4
	LastRaceName                 pgtype.Text
	Nationality                  string
	NationalityCountryID         string
	NationalityCountryCode       string
	PlaceOfBirth                 string
	PodiumCount                  int32
	QualifyingEntryCount         int32
	QualifyingP1Count            int32
	RaceEntryCount               int32
	RaceStartCount               int32
	RefreshID                    int64
	SecondNationalityCountryID   pgtype.Text
	SecondNationalityCountryCode pgtype.Text
	SprintEntryCount             int32
	SprintStartCount             int32
	StartCount                   int32
	TotalPoints                  pgtype.Numeric
	TotalPointsX100              int32
	WinCount                     int32
}

type EffoneDriverSeasonSummary struct {
	AverageQualifyingPosition pgtype.Numeric
	ChampionshipWon           bool
	ConstructorID             string
	DriverCode                string
	DriverID                  string
	DriverName                string
	EntryCount                int32
	FastestLapCount           int32
	FinalPoints               pgtype.Numeric
	FinalPointsX100           pgtype.Int4
	FinalPosition             pgtype.Int4
	FinalPositionText         pgtype.Text
	PodiumCount               int32
	PointsDelta               pgtype.Numeric
	PointsDeltaX100           int32
	QualifyingEntryCount      int32
	QualifyingP1Count         int32
	QualifyingPositionCount   int32
	RaceEntryCount            int32
	RacePoints                pgtype.Numeric
	RacePointsX100            int32
	RaceStartCount            int32
	RefreshID                 int64
	Season                    int32
	SprintEntryCount          int32
	SprintPoints              pgtype.Numeric
	SprintPointsX100          int32
	SprintStartCount          int32
	StartCount                int32
	TotalPoints               pgtype.Numeric
	TotalPointsX100           int32
	WinCount                  int32
}

type EffoneDriverStandingsSnapshot struct {
	ChampionshipWon    bool
	DriverCode         string
	DriverID           string
	DriverName         string
	Points             pgtype.Numeric
	PointsGained       pgtype.Numeric
	PointsGainedX100   pgtype.Int4
	PointsX100         int32
	Position           pgtype.Int4
	PositionChange     pgtype.Int4
	PositionText       string
	PreviousPoints     pgtype.Numeric
	PreviousPointsX100 pgtype.Int4
	PreviousPosition   pgtype.Int4
	RaceID             int32
	RaceRound          int32
	RefreshID          int64
	Season             int32
}

type EffoneFastestLap struct {
	CarNumber            pgtype.Int4
	CircuitID            string
	ConstructorID        string
	ConstructorName      string
	DriverCode           string
	DriverID             string
	DriverName           string
	EngineManufacturerID string
	FastestLapOrder      int32
	FastestLapPosition   pgtype.Int4
	Gap                  pgtype.Text
	GapMs                pgtype.Int4
	Interval             pgtype.Text
	IntervalMs           pgtype.Int4
	LapNumber            pgtype.Int4
	LapTime              pgtype.Text
	LapTimeMs            pgtype.Int4
	PositionText         string
	RaceDate             pgtype.Date
	RaceID               int32
	RaceName             string
	RaceRound            int32
	RefreshID            int64
	Season               int32
	TyreManufacturerID   string
}

type EffonePitStop struct {
	CarNumber            pgtype.Int4
	CircuitID            string
	ConstructorID        string
	ConstructorName      string
	DriverCode           string
	DriverID             string
	DriverName           string
	Duration             pgtype.Text
	DurationMs           pgtype.Int4
	EngineManufacturerID string
	LapNumber            int32
	PositionText         string
	RaceDate             pgtype.Date
	RaceID               int32
	RaceName             string
	RaceRound            int32
	RefreshID            int64
	Season               int32
	StopNumber           int32
	StopOrder            int32
	StopPosition         pgtype.Int4
	TyreManufacturerID   string
}

type EffoneQualifyingResult struct {
	AdvancedToQ2         bool
	AdvancedToQ3         bool
	BestQualifyingMs     pgtype.Int4
	BestQualifyingTime   pgtype.Text
	CarNumber            pgtype.Int4
	CircuitID            string
	ConstructorID        string
	ConstructorName      string
	DriverCode           string
	DriverID             string
	DriverName           string
	EngineManufacturerID string
	Gap                  pgtype.Text
	GapMs                pgtype.Int4
	Interval             pgtype.Text
	IntervalMs           pgtype.Int4
	IsEntry              bool
	IsQualifyingP1       bool
	Laps                 pgtype.Int4
	PositionText         string
	Q1                   pgtype.Text
	Q1Ms                 pgtype.Int4
	Q2                   pgtype.Text
	Q2Ms                 pgtype.Int4
	Q3                   pgtype.Text
	Q3Ms                 pgtype.Int4
	QualifyingOrder      pgtype.Int4
	QualifyingPosition   pgtype.Int4
	RaceDate             pgtype.Date
	RaceID               int32
	RaceName             string
	RaceRound            int32
	RefreshID            int64
	Season               int32
	TyreManufacturerID   string
}

type EffoneRace struct {
	CircuitID                   string
	CircuitLayoutID             string
	CircuitType                 string
	CourseLengthKm              pgtype.Numeric
	Direction                   string
	Fp1Date                     pgtype.Date
	Fp1Time                     pgtype.Time
	Fp2Date                     pgtype.Date
	Fp2Time                     pgtype.Time
	Fp3Date                     pgtype.Date
	Fp3Time                     pgtype.Time
	GrandPrixID                 string
	GrandPrixName               string
	PoleDriverID                pgtype.Text
	PoleDriverName              pgtype.Text
	QualifyingDate              pgtype.Date
	QualifyingFormat            string
	QualifyingTime              pgtype.Time
	RaceDate                    pgtype.Date
	RaceDistanceKm              pgtype.Numeric
	RaceID                      int32
	RaceLaps                    int32
	RaceName                    string
	RaceOfficialName            string
	RaceRound                   int32
	RaceTime                    pgtype.Time
	RefreshID                   int64
	ScheduledDistanceKm         pgtype.Numeric
	ScheduledLaps               pgtype.Int4
	Season                      int32
	SprintDate                  pgtype.Date
	SprintQualifyingDate        pgtype.Date
	SprintQualifyingFormat      pgtype.Text
	SprintQualifyingTime        pgtype.Time
	SprintTime                  pgtype.Time
	SprintWinnerConstructorID   pgtype.Text
	SprintWinnerConstructorName pgtype.Text
	SprintWinnerDriverID        pgtype.Text
	SprintWinnerDriverName      pgtype.Text
	Turns                       int32
	WinnerConstructorID         pgtype.Text
	WinnerConstructorName       pgtype.Text
	WinnerDriverID              pgtype.Text
	WinnerDriverName            pgtype.Text
}

type EffoneRaceResult struct {
	CarNumber            pgtype.Int4
	CircuitID            string
	ConstructorID        string
	ConstructorName      string
	DriverCode           string
	DriverID             string
	DriverName           string
	ElapsedTime          pgtype.Text
	ElapsedTimeMs        pgtype.Int4
	EngineManufacturerID string
	FinishOrder          int32
	FinishPosition       pgtype.Int4
	Gap                  pgtype.Text
	GapLaps              pgtype.Int4
	GapMs                pgtype.Int4
	GridPosition         pgtype.Int4
	Interval             pgtype.Text
	IntervalMs           pgtype.Int4
	IsClassifiedFinish   bool
	IsDnf                bool
	IsDriverOfTheDay     bool
	IsEntry              bool
	IsFastestLap         bool
	IsGrandSlam          bool
	IsGridP1             bool
	IsPodium             bool
	IsPointsFinish       bool
	IsPolePosition       bool
	IsStart              bool
	IsWin                bool
	LapsCompleted        pgtype.Int4
	PitStopCount         pgtype.Int4
	Points               pgtype.Numeric
	PointsX100           int32
	PositionsGained      pgtype.Int4
	PositionText         string
	QualifyingPosition   pgtype.Int4
	RaceDate             pgtype.Date
	RaceID               int32
	RaceName             string
	RaceRound            int32
	RefreshID            int64
	Season               int32
	Status               pgtype.Text
	StatusCategory       string
	TimePenalty          pgtype.Text
	TimePenaltyMs        pgtype.Int4
	TyreManufacturerID   string
}

// Metadata for source data refreshes.
type EffoneRefreshRun struct {
	RefreshID     int64
	StartedAt     pgtype.Timestamptz
	FinishedAt    pgtype.Timestamptz
	DurationMs    pgtype.Int4
	SourceVersion pgtype.Text
	Status        string
	// Per-table row counts captured by refreshes.
	RowCounts    []byte
	ErrorMessage pgtype.Text
	Notes        pgtype.Text
}

type EffoneSeason struct {
	ConstructorCount   int32
	DriverCount        int32
	FirstRaceDate      pgtype.Date
	LastRaceDate       pgtype.Date
	RaceCount          int32
	RefreshID          int64
	Season             int32
	SprintCount        int32
	WccConstructorID   pgtype.Text
	WccConstructorName pgtype.Text
	WdcDriverID        pgtype.Text
	WdcDriverName      pgtype.Text
}

type EffoneSprintResult struct {
	CarNumber            pgtype.Int4
	CircuitID            string
	ConstructorID        string
	ConstructorName      string
	DriverCode           string
	DriverID             string
	DriverName           string
	ElapsedTime          pgtype.Text
	ElapsedTimeMs        pgtype.Int4
	EngineManufacturerID string
	FinishOrder          int32
	FinishPosition       pgtype.Int4
	Gap                  pgtype.Text
	GapLaps              pgtype.Int4
	GapMs                pgtype.Int4
	GridPosition         pgtype.Int4
	Interval             pgtype.Text
	IntervalMs           pgtype.Int4
	IsClassifiedFinish   bool
	IsDnf                bool
	IsEntry              bool
	IsGridP1             bool
	IsPodium             bool
	IsPointsFinish       bool
	IsStart              bool
	IsWin                bool
	LapsCompleted        pgtype.Int4
	Points               pgtype.Numeric
	PointsX100           int32
	PositionsGained      pgtype.Int4
	PositionText         string
	QualifyingPosition   pgtype.Int4
	RaceDate             pgtype.Date
	RaceID               int32
	RaceName             string
	RaceRound            int32
	RefreshID            int64
	Season               int32
	Status               pgtype.Text
	StatusCategory       string
	TimePenalty          pgtype.Text
	TimePenaltyMs        pgtype.Int4
	TyreManufacturerID   string
}
