// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	CreateRefreshRun(ctx context.Context, arg CreateRefreshRunParams) (int64, error)
	GetCircuitInfo(ctx context.Context, circuitID string) (GetCircuitInfoRow, error)
	GetDriverSummary(ctx context.Context, driverID string) (GetDriverSummaryRow, error)
	GetRacesByCircuitId(ctx context.Context, circuitID string) ([]GetRacesByCircuitIdRow, error)
	ListCircuits(ctx context.Context) ([]ListCircuitsRow, error)
	ListConstructors(ctx context.Context) ([]ListConstructorsRow, error)
	ListDriverSeasons(ctx context.Context, driverID string) ([]ListDriverSeasonsRow, error)
	ListSeasons(ctx context.Context) ([]ListSeasonsRow, error)
	MarkRefreshFailed(ctx context.Context, arg MarkRefreshFailedParams) error
	MarkRefreshSucceeded(ctx context.Context, arg MarkRefreshSucceededParams) error
}

var _ Querier = (*Queries)(nil)
