// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	GetCircuitInfo(ctx context.Context, circuitID string) (GetCircuitInfoRow, error)
	GetConstructorSummary(ctx context.Context, constructorID string) (GetConstructorSummaryRow, error)
	GetDriverRace(ctx context.Context, season int32, raceRound int32, driverID string) (GetDriverRaceRow, error)
	GetDriverSeason(ctx context.Context, season int32, driverID string) (GetDriverSeasonRow, error)
	GetDriverSprint(ctx context.Context, season int32, raceRound int32, driverID string) (GetDriverSprintRow, error)
	GetDriverSummary(ctx context.Context, driverID string) (GetDriverSummaryRow, error)
	GetRaceDetail(ctx context.Context, season int32, raceRound int32) (GetRaceDetailRow, error)
	GetRacesByCircuitId(ctx context.Context, circuitID string) ([]GetRacesByCircuitIdRow, error)
	ListCircuits(ctx context.Context) ([]ListCircuitsRow, error)
	ListConstructorLineage(ctx context.Context, constructorID string) ([]ListConstructorLineageRow, error)
	ListConstructorSeasonDriverSummaries(ctx context.Context, season int32, constructorID string) ([]ListConstructorSeasonDriverSummariesRow, error)
	ListConstructorSeasonDrivers(ctx context.Context, constructorID string) ([]ListConstructorSeasonDriversRow, error)
	ListConstructorSeasonEntries(ctx context.Context, season int32, constructorID string) ([]ListConstructorSeasonEntriesRow, error)
	ListConstructorSeasonProgression(ctx context.Context, season int32, constructorID string) ([]ListConstructorSeasonProgressionRow, error)
	ListConstructorSeasonResults(ctx context.Context, season int32, constructorID string) ([]ListConstructorSeasonResultsRow, error)
	ListConstructorSeasons(ctx context.Context, constructorID string) ([]ListConstructorSeasonsRow, error)
	ListConstructors(ctx context.Context) ([]ListConstructorsRow, error)
	ListDriverRacePitStops(ctx context.Context, raceID int32, driverID string) ([]ListDriverRacePitStopsRow, error)
	ListDriverSeasonRaces(ctx context.Context, season int32, driverID string) ([]ListDriverSeasonRacesRow, error)
	ListDriverSeasons(ctx context.Context, driverID string) ([]ListDriverSeasonsRow, error)
	ListDrivers(ctx context.Context) ([]ListDriversRow, error)
	ListRaceLapTimes(ctx context.Context, raceID int32, session string) ([]ListRaceLapTimesRow, error)
	ListRaceResults(ctx context.Context, raceID int32) ([]ListRaceResultsRow, error)
	ListSeasonCalendar(ctx context.Context, season int32) ([]ListSeasonCalendarRow, error)
	ListSeasonConstructorStandings(ctx context.Context, season int32) ([]ListSeasonConstructorStandingsRow, error)
	ListSeasonDriverProgression(ctx context.Context, season int32, driverIds []string) ([]ListSeasonDriverProgressionRow, error)
	ListSeasonDriverStandings(ctx context.Context, season int32) ([]ListSeasonDriverStandingsRow, error)
	ListSeasons(ctx context.Context) ([]ListSeasonsRow, error)
}

var _ Querier = (*Queries)(nil)
