// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	ListConstructors(ctx context.Context) ([]ListConstructorsRow, error)
	ListSeasons(ctx context.Context) ([]ListSeasonsRow, error)
}

var _ Querier = (*Queries)(nil)
