// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: races.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jsec/drs/internal/dbtypes"
)

const getRaceDetail = `-- name: GetRaceDetail :one
SELECT
    r.race_id,
    r.season,
    r.race_round,
    r.race_name,
    r.race_date,
    ci.circuit_name,
    r.race_laps,
    r.pole_driver_id,
    pole.driver_code AS pole_code,
    r.winner_driver_id,
    r.winner_driver_code,
    fl.driver_id AS fastest_lap_driver_id,
    fl.driver_code AS fastest_lap_code,
    fl.lap_time AS fastest_lap_time
FROM effone.races AS r
JOIN effone.circuits AS ci
    ON r.circuit_id = ci.circuit_id
LEFT JOIN effone.drivers AS pole
    ON r.pole_driver_id = pole.driver_id
LEFT JOIN effone.fastest_laps AS fl
    ON r.race_id = fl.race_id
    AND fl.fastest_lap_order = 1
WHERE r.season = $1
    AND r.race_round = $2
`

type GetRaceDetailParams struct {
	Season    int32
	RaceRound int32
}

type GetRaceDetailRow struct {
	RaceID             int32
	Season             int32
	RaceRound          int32
	RaceName           string
	RaceDate           dbtypes.Date
	CircuitName        string
	RaceLaps           int32
	PoleDriverID       pgtype.Text
	PoleCode           pgtype.Text
	WinnerDriverID     pgtype.Text
	WinnerDriverCode   pgtype.Text
	FastestLapDriverID pgtype.Text
	FastestLapCode     pgtype.Text
	FastestLapTime     pgtype.Text
}

func (q *Queries) GetRaceDetail(ctx context.Context, arg GetRaceDetailParams) (GetRaceDetailRow, error) {
	row := q.db.QueryRow(ctx, getRaceDetail, arg.Season, arg.RaceRound)
	var i GetRaceDetailRow
	err := row.Scan(
		&i.RaceID,
		&i.Season,
		&i.RaceRound,
		&i.RaceName,
		&i.RaceDate,
		&i.CircuitName,
		&i.RaceLaps,
		&i.PoleDriverID,
		&i.PoleCode,
		&i.WinnerDriverID,
		&i.WinnerDriverCode,
		&i.FastestLapDriverID,
		&i.FastestLapCode,
		&i.FastestLapTime,
	)
	return i, err
}

const listRaceLapTimes = `-- name: ListRaceLapTimes :many
SELECT
    lt.driver_id,
    lt.lap_number,
    lt.position,
    lt.lap_time_ms
FROM effone.lap_times AS lt
WHERE lt.race_id = $1
    AND lt.session = $2
ORDER BY lt.driver_id, lt.lap_number
`

type ListRaceLapTimesParams struct {
	RaceID  int32
	Session string
}

type ListRaceLapTimesRow struct {
	DriverID  string
	LapNumber int32
	Position  dbtypes.Int4
	LapTimeMs int32
}

func (q *Queries) ListRaceLapTimes(ctx context.Context, arg ListRaceLapTimesParams) ([]ListRaceLapTimesRow, error) {
	rows, err := q.db.Query(ctx, listRaceLapTimes, arg.RaceID, arg.Session)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRaceLapTimesRow
	for rows.Next() {
		var i ListRaceLapTimesRow
		if err := rows.Scan(
			&i.DriverID,
			&i.LapNumber,
			&i.Position,
			&i.LapTimeMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRaceResults = `-- name: ListRaceResults :many
SELECT
    rr.finish_order AS position,
    rr.position_text AS position_label,
    rr.driver_id,
    rr.driver_code AS code,
    rr.driver_name AS name,
    d.last_name,
    rr.constructor_id,
    rr.constructor_name,
    c.primary_color_hex AS constructor_color,
    rr.grid_position,
    rr.elapsed_time,
    rr.gap,
    rr.status,
    rr.points::double precision AS points
FROM effone.race_results AS rr
JOIN effone.drivers AS d
    ON rr.driver_id = d.driver_id
LEFT JOIN effone.constructors AS c
    ON rr.constructor_id = c.constructor_id
WHERE rr.race_id = $1
ORDER BY rr.finish_order
`

type ListRaceResultsRow struct {
	Position         int32
	PositionLabel    string
	DriverID         string
	Code             string
	Name             string
	LastName         string
	ConstructorID    string
	ConstructorName  string
	ConstructorColor pgtype.Text
	GridPosition     dbtypes.Int4
	ElapsedTime      pgtype.Text
	Gap              pgtype.Text
	Status           pgtype.Text
	Points           float64
}

func (q *Queries) ListRaceResults(ctx context.Context, raceID int32) ([]ListRaceResultsRow, error) {
	rows, err := q.db.Query(ctx, listRaceResults, raceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRaceResultsRow
	for rows.Next() {
		var i ListRaceResultsRow
		if err := rows.Scan(
			&i.Position,
			&i.PositionLabel,
			&i.DriverID,
			&i.Code,
			&i.Name,
			&i.LastName,
			&i.ConstructorID,
			&i.ConstructorName,
			&i.ConstructorColor,
			&i.GridPosition,
			&i.ElapsedTime,
			&i.Gap,
			&i.Status,
			&i.Points,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
