// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_runs.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshRun = `-- name: CreateRefreshRun :one
INSERT INTO effone.refresh_runs (status, source_version)
VALUES ($1, $2)
RETURNING refresh_id
`

type CreateRefreshRunParams struct {
	Status        string
	SourceVersion pgtype.Text
}

func (q *Queries) CreateRefreshRun(ctx context.Context, arg CreateRefreshRunParams) (int64, error) {
	row := q.db.QueryRow(ctx, createRefreshRun, arg.Status, arg.SourceVersion)
	var refresh_id int64
	err := row.Scan(&refresh_id)
	return refresh_id, err
}

const markRefreshFailed = `-- name: MarkRefreshFailed :exec
UPDATE effone.refresh_runs
SET
    status = 'failed',
    finished_at = now(),
    duration_ms = extract(EPOCH FROM (now() - started_at)) * 1000,
    row_counts = '{}'::jsonb
WHERE refresh_id = $1
`

func (q *Queries) MarkRefreshFailed(ctx context.Context, refreshID int64) error {
	_, err := q.db.Exec(ctx, markRefreshFailed, refreshID)
	return err
}

const markRefreshSucceeded = `-- name: MarkRefreshSucceeded :exec
UPDATE effone.refresh_runs
SET
    status = 'succeeded',
    finished_at = now(),
    duration_ms = extract(EPOCH FROM (now() - started_at)) * 1000,
    row_counts = $2
WHERE refresh_id = $1
`

type MarkRefreshSucceededParams struct {
	RefreshID int64
	RowCounts []byte
}

func (q *Queries) MarkRefreshSucceeded(ctx context.Context, arg MarkRefreshSucceededParams) error {
	_, err := q.db.Exec(ctx, markRefreshSucceeded, arg.RefreshID, arg.RowCounts)
	return err
}
