// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_runs.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshRun = `-- name: CreateRefreshRun :one
INSERT INTO effone.refresh_runs (status)
VALUES ($1)
RETURNING refresh_id
`

func (q *Queries) CreateRefreshRun(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, createRefreshRun, status)
	var refresh_id int64
	err := row.Scan(&refresh_id)
	return refresh_id, err
}

const markRefreshFailed = `-- name: MarkRefreshFailed :exec
UPDATE effone.refresh_runs
SET
    status = 'failed',
    finished_at = now(),
    row_counts = '{}'::jsonb,
    error_message = $2
WHERE refresh_id = $1
`

func (q *Queries) MarkRefreshFailed(ctx context.Context, refreshID int64, errorMessage pgtype.Text) error {
	_, err := q.db.Exec(ctx, markRefreshFailed, refreshID, errorMessage)
	return err
}

const markRefreshSucceeded = `-- name: MarkRefreshSucceeded :exec
UPDATE effone.refresh_runs
SET
    status = 'succeeded',
    finished_at = now(),
    row_counts = $2
WHERE refresh_id = $1
`

func (q *Queries) MarkRefreshSucceeded(ctx context.Context, refreshID int64, rowCounts []byte) error {
	_, err := q.db.Exec(ctx, markRefreshSucceeded, refreshID, rowCounts)
	return err
}
