// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seasons.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jsec/drs/internal/dbtypes"
)

const listSeasonConstructorStandings = `-- name: ListSeasonConstructorStandings :many
WITH latest_round AS (
    SELECT max(race_round) AS race_round
    FROM effone.constructor_standings_snapshots
    WHERE season = $1
)
SELECT
    css.position,
    css.position_text AS position_label,
    css.points::double precision AS points,
    css.constructor_id,
    css.constructor_name AS name,
    c.primary_color_hex AS constructor_color
FROM effone.constructor_standings_snapshots AS css
JOIN latest_round
    ON css.race_round = latest_round.race_round
JOIN effone.constructors AS c
    ON css.constructor_id = c.constructor_id
WHERE css.season = $1
ORDER BY css.position NULLS LAST, css.constructor_name
`

type ListSeasonConstructorStandingsRow struct {
	Position         dbtypes.Int4
	PositionLabel    string
	Points           float64
	ConstructorID    string
	Name             string
	ConstructorColor string
}

func (q *Queries) ListSeasonConstructorStandings(ctx context.Context, season int32) ([]ListSeasonConstructorStandingsRow, error) {
	rows, err := q.db.Query(ctx, listSeasonConstructorStandings, season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeasonConstructorStandingsRow
	for rows.Next() {
		var i ListSeasonConstructorStandingsRow
		if err := rows.Scan(
			&i.Position,
			&i.PositionLabel,
			&i.Points,
			&i.ConstructorID,
			&i.Name,
			&i.ConstructorColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasonDriverProgression = `-- name: ListSeasonDriverProgression :many
SELECT
    dss.race_round,
    dss.driver_id,
    dss.driver_code AS code,
    dss.points::double precision AS points
FROM effone.driver_standings_snapshots AS dss
WHERE dss.season = $1
ORDER BY dss.driver_id, dss.race_round
`

type ListSeasonDriverProgressionRow struct {
	RaceRound int32
	DriverID  string
	Code      string
	Points    float64
}

func (q *Queries) ListSeasonDriverProgression(ctx context.Context, season int32) ([]ListSeasonDriverProgressionRow, error) {
	rows, err := q.db.Query(ctx, listSeasonDriverProgression, season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeasonDriverProgressionRow
	for rows.Next() {
		var i ListSeasonDriverProgressionRow
		if err := rows.Scan(
			&i.RaceRound,
			&i.DriverID,
			&i.Code,
			&i.Points,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasonDriverStandings = `-- name: ListSeasonDriverStandings :many
WITH latest_round AS (
    SELECT max(race_round) AS race_round
    FROM effone.driver_standings_snapshots
    WHERE season = $1
)
SELECT
    dss.position,
    dss.position_text AS position_label,
    dss.points::double precision AS points,
    dss.driver_id,
    dss.driver_code AS code,
    dss.driver_name AS name,
    d.nationality AS country,
    d.nationality_country_code AS country_code,
    dss.constructor_id,
    c.constructor_name,
    c.primary_color_hex AS constructor_color,
    dss.car_number,
    dss.win_count AS wins,
    dss.podium_count AS podiums,
    dss.qualifying_p1_count AS poles
FROM effone.driver_standings_snapshots AS dss
JOIN latest_round
    ON dss.race_round = latest_round.race_round
JOIN effone.drivers AS d
    ON dss.driver_id = d.driver_id
LEFT JOIN effone.constructors AS c
    ON dss.constructor_id = c.constructor_id
WHERE dss.season = $1
ORDER BY dss.position NULLS LAST, dss.driver_name
`

type ListSeasonDriverStandingsRow struct {
	Position         dbtypes.Int4
	PositionLabel    string
	Points           float64
	DriverID         string
	Code             string
	Name             string
	Country          string
	CountryCode      string
	ConstructorID    pgtype.Text
	ConstructorName  pgtype.Text
	ConstructorColor pgtype.Text
	CarNumber        dbtypes.Int4
	Wins             int32
	Podiums          int32
	Poles            int32
}

func (q *Queries) ListSeasonDriverStandings(ctx context.Context, season int32) ([]ListSeasonDriverStandingsRow, error) {
	rows, err := q.db.Query(ctx, listSeasonDriverStandings, season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeasonDriverStandingsRow
	for rows.Next() {
		var i ListSeasonDriverStandingsRow
		if err := rows.Scan(
			&i.Position,
			&i.PositionLabel,
			&i.Points,
			&i.DriverID,
			&i.Code,
			&i.Name,
			&i.Country,
			&i.CountryCode,
			&i.ConstructorID,
			&i.ConstructorName,
			&i.ConstructorColor,
			&i.CarNumber,
			&i.Wins,
			&i.Podiums,
			&i.Poles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasons = `-- name: ListSeasons :many
SELECT
    s.season,
    s.race_count,
    s.constructor_count,
    s.wdc_driver_id,
    s.wdc_driver_name,
    d.nationality_country_code AS wdc_country_code,
    s.wcc_constructor_id,
    s.wcc_constructor_name,
    c.primary_color_hex AS wcc_color
FROM effone.seasons s
INNER JOIN effone.drivers d ON s.wdc_driver_id = d.driver_id
LEFT JOIN effone.constructors c ON s.wcc_constructor_id = c.constructor_id
ORDER BY s.season DESC
`

type ListSeasonsRow struct {
	Season             int32
	RaceCount          int32
	ConstructorCount   int32
	WdcDriverID        pgtype.Text
	WdcDriverName      pgtype.Text
	WdcCountryCode     string
	WccConstructorID   pgtype.Text
	WccConstructorName pgtype.Text
	WccColor           pgtype.Text
}

func (q *Queries) ListSeasons(ctx context.Context) ([]ListSeasonsRow, error) {
	rows, err := q.db.Query(ctx, listSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeasonsRow
	for rows.Next() {
		var i ListSeasonsRow
		if err := rows.Scan(
			&i.Season,
			&i.RaceCount,
			&i.ConstructorCount,
			&i.WdcDriverID,
			&i.WdcDriverName,
			&i.WdcCountryCode,
			&i.WccConstructorID,
			&i.WccConstructorName,
			&i.WccColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
