// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seasons.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listSeasons = `-- name: ListSeasons :many
SELECT
    s.season,
    s.race_count,
    s.constructor_count,
    s.wdc_driver_id,
    s.wdc_driver_name,
    d.nationality_country_code AS wdc_country_code,
    s.wcc_constructor_id,
    s.wcc_constructor_name,
    c.primary_color_hex AS wcc_color
FROM effone.seasons s
INNER JOIN effone.drivers d ON s.wdc_driver_id = d.driver_id
LEFT JOIN effone.constructors c ON s.wcc_constructor_id = c.constructor_id
ORDER BY s.season DESC
`

type ListSeasonsRow struct {
	Season             int32
	RaceCount          int32
	ConstructorCount   int32
	WdcDriverID        pgtype.Text
	WdcDriverName      pgtype.Text
	WdcCountryCode     string
	WccConstructorID   pgtype.Text
	WccConstructorName pgtype.Text
	WccColor           pgtype.Text
}

func (q *Queries) ListSeasons(ctx context.Context) ([]ListSeasonsRow, error) {
	rows, err := q.db.Query(ctx, listSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeasonsRow
	for rows.Next() {
		var i ListSeasonsRow
		if err := rows.Scan(
			&i.Season,
			&i.RaceCount,
			&i.ConstructorCount,
			&i.WdcDriverID,
			&i.WdcDriverName,
			&i.WdcCountryCode,
			&i.WccConstructorID,
			&i.WccConstructorName,
			&i.WccColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
