version: "2"

linters:
  enable:
    - bodyclose
    - misspell
    - testifylint
  exclusions:
    rules:
      - path: (\.sql\.go|db\.go|models\.go)$
        linters:
          - all

formatters:
  enable:
    - gofmt
    - goimports
