version: "3"

dotenv: [".env"]

vars:
  APP_PKG: ./cmd/drs

tasks:
  build:
    cmds:
      - go build -o bin/drs {{.APP_PKG}}

  default:
    cmds:
      - task --list-all
    silent: true

  dev:
    cmds:
      - air

  etl:build:
    cmds:
      - go run {{.APP_PKG}} etl build

  etl:check:
    cmds:
      - task: etl:format-check

  etl:dbt-debug:
    dir: etl
    cmds:
      - uv run dbt debug --project-dir ./dbt --profiles-dir ./dbt

  etl:dbt-deps:
    dir: etl
    cmds:
      - uv run dbt deps --project-dir ./dbt --profiles-dir ./dbt

  etl:dbt-parse:
    dir: etl
    cmds:
      - uv run dbt parse --project-dir ./dbt --profiles-dir ./dbt

  etl:format:
    dir: etl
    cmds:
      - uv run sqlfmt dbt/models dbt/macros dbt/tests

  etl:format-check:
    dir: etl
    cmds:
      - uv run sqlfmt --check dbt/models dbt/macros dbt/tests

  etl:load:
    cmds:
      - go run {{.APP_PKG}} etl load

  etl:migrate:
    dir: etl
    cmds:
      - goose -table app_goose_db_version -dir ./migrations postgres "$DATABASE_URL" up

  etl:migrate-down:
    dir: etl
    cmds:
      - goose -table app_goose_db_version -dir ./migrations postgres "$DATABASE_URL" down

  etl:migrate-status:
    dir: etl
    cmds:
      - goose -table app_goose_db_version -dir ./migrations postgres "$DATABASE_URL" status

  etl:refresh:
    cmds:
      - go run {{.APP_PKG}} etl refresh

  gen:
    cmds:
      - task: gen:schema
      - task: gen:sqlc
      - task: gen:tygo

  gen:schema:
    cmds:
      - >-
        pg_dump "$DATABASE_URL" -n effone --schema-only --no-owner --no-privileges
        | grep -vE '^\\'
        > internal/database/schema.sql

  gen:sqlc:
    dir: internal/database
    cmds:
      - sqlc generate

  gen:tygo:
    cmds:
      - tygo generate

  lint:
    cmds:
      - golangci-lint run

  run:
    cmds:
      - go run {{.APP_PKG}} serve


  test:
    cmds:
      - go test ./...
