select
    id as driver_id,
    name as driver_name,
    first_name,
    last_name,
    full_name as driver_full_name,
    abbreviation as driver_code,
    permanent_number::integer as driver_number,
    gender,
    date_of_birth,
    date_of_death,
    place_of_birth,
    country_of_birth_country_id,
    nationality_country_id,
    second_nationality_country_id,
    best_championship_position,
    best_starting_grid_position,
    best_race_result,
    best_sprint_race_result,
    total_championship_wins,
    total_race_entries,
    total_race_starts,
    total_race_wins,
    total_race_laps,
    total_podiums,
    total_points,
    total_championship_points,
    total_pole_positions,
    total_fastest_laps,
    total_sprint_race_starts,
    total_sprint_race_wins,
    total_driver_of_the_day,
    total_grand_slams
from {{ source("f1db", "driver") }}
