select
    id as race_id,
    year as season,
    round as race_round,
    date as race_date,
    "time"::time as race_time,
    grand_prix_id,
    official_name as race_official_name,
    qualifying_format,
    sprint_qualifying_format,
    circuit_id,
    circuit_layout_id,
    circuit_type,
    direction,
    course_length as course_length_km,
    turns,
    laps as race_laps,
    distance as race_distance_km,
    scheduled_laps,
    scheduled_distance as scheduled_distance_km,
    drivers_championship_decider,
    constructors_championship_decider,
    pre_qualifying_date,
    pre_qualifying_time::time as pre_qualifying_time,
    free_practice_1_date,
    free_practice_1_time::time as free_practice_1_time,
    free_practice_2_date,
    free_practice_2_time::time as free_practice_2_time,
    free_practice_3_date,
    free_practice_3_time::time as free_practice_3_time,
    free_practice_4_date,
    free_practice_4_time::time as free_practice_4_time,
    qualifying_1_date,
    qualifying_1_time::time as qualifying_1_time,
    qualifying_2_date,
    qualifying_2_time::time as qualifying_2_time,
    qualifying_date,
    qualifying_time::time as qualifying_time,
    sprint_qualifying_date,
    sprint_qualifying_time::time as sprint_qualifying_time,
    sprint_race_date,
    sprint_race_time::time as sprint_race_time,
    warming_up_date,
    warming_up_time::time as warming_up_time
from {{ source("f1db", "race") }}
