/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CircuitsIndexRouteImport } from './routes/circuits/index'
import { Route as CircuitsCircuitIdRouteImport } from './routes/circuits/$circuitId'
import { Route as ConstructorsIndexRouteImport } from './routes/constructors/index'
import { Route as DriversIndexRouteImport } from './routes/drivers/index'
import { Route as DriversDriverIdRouteImport } from './routes/drivers/$driverId'
import { Route as SeasonsIndexRouteImport } from './routes/seasons/index'
import { Route as SeasonsYearIndexRouteImport } from './routes/seasons/$year/index'
import { Route as SeasonsYearCalendarRouteImport } from './routes/seasons/$year/calendar'
import { Route as SeasonsYearStandingsRouteImport } from './routes/seasons/$year/standings'
import { Route as SeasonsYearDriversDriverIdRouteImport } from './routes/seasons/$year/drivers/$driverId'
import { Route as SeasonsYearRacesRoundRouteImport } from './routes/seasons/$year/races/$round'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitsIndexRoute = CircuitsIndexRouteImport.update({
  id: '/circuits/',
  path: '/circuits/',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitsCircuitIdRoute = CircuitsCircuitIdRouteImport.update({
  id: '/circuits/$circuitId',
  path: '/circuits/$circuitId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructorsIndexRoute = ConstructorsIndexRouteImport.update({
  id: '/constructors/',
  path: '/constructors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversIndexRoute = DriversIndexRouteImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversDriverIdRoute = DriversDriverIdRouteImport.update({
  id: '/drivers/$driverId',
  path: '/drivers/$driverId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsIndexRoute = SeasonsIndexRouteImport.update({
  id: '/seasons/',
  path: '/seasons/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsYearIndexRoute = SeasonsYearIndexRouteImport.update({
  id: '/seasons/$year/',
  path: '/seasons/$year/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsYearCalendarRoute = SeasonsYearCalendarRouteImport.update({
  id: '/seasons/$year/calendar',
  path: '/seasons/$year/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsYearStandingsRoute = SeasonsYearStandingsRouteImport.update({
  id: '/seasons/$year/standings',
  path: '/seasons/$year/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsYearDriversDriverIdRoute =
  SeasonsYearDriversDriverIdRouteImport.update({
    id: '/seasons/$year/drivers/$driverId',
    path: '/seasons/$year/drivers/$driverId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SeasonsYearRacesRoundRoute = SeasonsYearRacesRoundRouteImport.update({
  id: '/seasons/$year/races/$round',
  path: '/seasons/$year/races/$round',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/circuits/$circuitId': typeof CircuitsCircuitIdRoute
  '/drivers/$driverId': typeof DriversDriverIdRoute
  '/circuits/': typeof CircuitsIndexRoute
  '/constructors/': typeof ConstructorsIndexRoute
  '/drivers/': typeof DriversIndexRoute
  '/seasons/': typeof SeasonsIndexRoute
  '/seasons/$year/calendar': typeof SeasonsYearCalendarRoute
  '/seasons/$year/standings': typeof SeasonsYearStandingsRoute
  '/seasons/$year/': typeof SeasonsYearIndexRoute
  '/seasons/$year/drivers/$driverId': typeof SeasonsYearDriversDriverIdRoute
  '/seasons/$year/races/$round': typeof SeasonsYearRacesRoundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/circuits/$circuitId': typeof CircuitsCircuitIdRoute
  '/drivers/$driverId': typeof DriversDriverIdRoute
  '/circuits': typeof CircuitsIndexRoute
  '/constructors': typeof ConstructorsIndexRoute
  '/drivers': typeof DriversIndexRoute
  '/seasons': typeof SeasonsIndexRoute
  '/seasons/$year/calendar': typeof SeasonsYearCalendarRoute
  '/seasons/$year/standings': typeof SeasonsYearStandingsRoute
  '/seasons/$year': typeof SeasonsYearIndexRoute
  '/seasons/$year/drivers/$driverId': typeof SeasonsYearDriversDriverIdRoute
  '/seasons/$year/races/$round': typeof SeasonsYearRacesRoundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/circuits/$circuitId': typeof CircuitsCircuitIdRoute
  '/drivers/$driverId': typeof DriversDriverIdRoute
  '/circuits/': typeof CircuitsIndexRoute
  '/constructors/': typeof ConstructorsIndexRoute
  '/drivers/': typeof DriversIndexRoute
  '/seasons/': typeof SeasonsIndexRoute
  '/seasons/$year/calendar': typeof SeasonsYearCalendarRoute
  '/seasons/$year/standings': typeof SeasonsYearStandingsRoute
  '/seasons/$year/': typeof SeasonsYearIndexRoute
  '/seasons/$year/drivers/$driverId': typeof SeasonsYearDriversDriverIdRoute
  '/seasons/$year/races/$round': typeof SeasonsYearRacesRoundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/circuits/$circuitId'
    | '/drivers/$driverId'
    | '/circuits/'
    | '/constructors/'
    | '/drivers/'
    | '/seasons/'
    | '/seasons/$year/calendar'
    | '/seasons/$year/standings'
    | '/seasons/$year/'
    | '/seasons/$year/drivers/$driverId'
    | '/seasons/$year/races/$round'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/circuits/$circuitId'
    | '/drivers/$driverId'
    | '/circuits'
    | '/constructors'
    | '/drivers'
    | '/seasons'
    | '/seasons/$year/calendar'
    | '/seasons/$year/standings'
    | '/seasons/$year'
    | '/seasons/$year/drivers/$driverId'
    | '/seasons/$year/races/$round'
  id:
    | '__root__'
    | '/'
    | '/circuits/$circuitId'
    | '/drivers/$driverId'
    | '/circuits/'
    | '/constructors/'
    | '/drivers/'
    | '/seasons/'
    | '/seasons/$year/calendar'
    | '/seasons/$year/standings'
    | '/seasons/$year/'
    | '/seasons/$year/drivers/$driverId'
    | '/seasons/$year/races/$round'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CircuitsCircuitIdRoute: typeof CircuitsCircuitIdRoute
  DriversDriverIdRoute: typeof DriversDriverIdRoute
  CircuitsIndexRoute: typeof CircuitsIndexRoute
  ConstructorsIndexRoute: typeof ConstructorsIndexRoute
  DriversIndexRoute: typeof DriversIndexRoute
  SeasonsIndexRoute: typeof SeasonsIndexRoute
  SeasonsYearCalendarRoute: typeof SeasonsYearCalendarRoute
  SeasonsYearStandingsRoute: typeof SeasonsYearStandingsRoute
  SeasonsYearIndexRoute: typeof SeasonsYearIndexRoute
  SeasonsYearDriversDriverIdRoute: typeof SeasonsYearDriversDriverIdRoute
  SeasonsYearRacesRoundRoute: typeof SeasonsYearRacesRoundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuits/': {
      id: '/circuits/'
      path: '/circuits'
      fullPath: '/circuits/'
      preLoaderRoute: typeof CircuitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuits/$circuitId': {
      id: '/circuits/$circuitId'
      path: '/circuits/$circuitId'
      fullPath: '/circuits/$circuitId'
      preLoaderRoute: typeof CircuitsCircuitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constructors/': {
      id: '/constructors/'
      path: '/constructors'
      fullPath: '/constructors/'
      preLoaderRoute: typeof ConstructorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/': {
      id: '/drivers/'
      path: '/drivers'
      fullPath: '/drivers/'
      preLoaderRoute: typeof DriversIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/$driverId': {
      id: '/drivers/$driverId'
      path: '/drivers/$driverId'
      fullPath: '/drivers/$driverId'
      preLoaderRoute: typeof DriversDriverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons/': {
      id: '/seasons/'
      path: '/seasons'
      fullPath: '/seasons/'
      preLoaderRoute: typeof SeasonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons/$year/': {
      id: '/seasons/$year/'
      path: '/seasons/$year'
      fullPath: '/seasons/$year/'
      preLoaderRoute: typeof SeasonsYearIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons/$year/calendar': {
      id: '/seasons/$year/calendar'
      path: '/seasons/$year/calendar'
      fullPath: '/seasons/$year/calendar'
      preLoaderRoute: typeof SeasonsYearCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons/$year/standings': {
      id: '/seasons/$year/standings'
      path: '/seasons/$year/standings'
      fullPath: '/seasons/$year/standings'
      preLoaderRoute: typeof SeasonsYearStandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons/$year/drivers/$driverId': {
      id: '/seasons/$year/drivers/$driverId'
      path: '/seasons/$year/drivers/$driverId'
      fullPath: '/seasons/$year/drivers/$driverId'
      preLoaderRoute: typeof SeasonsYearDriversDriverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons/$year/races/$round': {
      id: '/seasons/$year/races/$round'
      path: '/seasons/$year/races/$round'
      fullPath: '/seasons/$year/races/$round'
      preLoaderRoute: typeof SeasonsYearRacesRoundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CircuitsCircuitIdRoute: CircuitsCircuitIdRoute,
  DriversDriverIdRoute: DriversDriverIdRoute,
  CircuitsIndexRoute: CircuitsIndexRoute,
  ConstructorsIndexRoute: ConstructorsIndexRoute,
  DriversIndexRoute: DriversIndexRoute,
  SeasonsIndexRoute: SeasonsIndexRoute,
  SeasonsYearCalendarRoute: SeasonsYearCalendarRoute,
  SeasonsYearStandingsRoute: SeasonsYearStandingsRoute,
  SeasonsYearIndexRoute: SeasonsYearIndexRoute,
  SeasonsYearDriversDriverIdRoute: SeasonsYearDriversDriverIdRoute,
  SeasonsYearRacesRoundRoute: SeasonsYearRacesRoundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
